export type Book = {
  id: string;
  title: string;
  author: string;
  cover: string;
  description: string;
  rating: number | null;
  source: string;
};

const martinusSearch = (title: string) =>
  `https://www.martinus.sk/search?q=${encodeURIComponent(title)}`;

export const books: Book[] = [
  {
    id: "revolucionar-jednej-slamky",
    title: "Revolucionár jednej slamky",
    author: "Masanobu Fukuoka",
    cover: "/covers/001.webp",
    description: "Filozofia prirodzeného hospodárenia, jednoduchosti a života v súlade s krajinou.",
    rating: null,
    source: martinusSearch("Revolucionár jednej slamky"),
  },
  {
    id: "sedliacky",
    title: "Sedliačky",
    author: "Joanna Kuciel-Frydryszak",
    cover: "/covers/002.webp",
    description: "Silná reportáž o živote vidieckych žien, ich práci, chudobe a odolnosti.",
    rating: 4.6,
    source: "https://www.martinus.sk/3596167-sedliacky/kniha",
  },
  {
    id: "casozber",
    title: "Časozber",
    author: "Filip Langstein",
    cover: "/covers/003.webp",
    description: "Historické sci-fi o vedeckej výprave do dávnych epoch Zeme a nečakanom signále.",
    rating: null,
    source: "https://www.martinus.sk/3736605-casozber/kniha",
  },
  {
    id: "ubavit-se-k-smrti",
    title: "Ubavit se k smrti",
    author: "Neil Postman",
    cover: "/covers/004.webp",
    description: "Klasická kritika spoločnosti, v ktorej sa verejná diskusia mení na zábavu.",
    rating: null,
    source: martinusSearch("Ubavit se k smrti"),
  },
  {
    id: "cesta-do-mozgu-a-spat",
    title: "Cesta do mozgu a späť",
    author: "Dominika Fričová",
    cover: "/covers/005.webp",
    description: "Zrozumiteľný sprievodca mozgom: ako ho pochopiť, trénovať a upokojiť.",
    rating: null,
    source: "https://www.martinus.sk/3933935-cesta-do-mozgu-a-spat/e-kniha",
  },
  {
    id: "zrkadlo",
    title: "Zrkadlo",
    author: "Karl Olsberg",
    cover: "/covers/006.webp",
    description: "Technologický triler o umelej inteligencii, identite a hranici medzi človekom a strojom.",
    rating: null,
    source: martinusSearch("Zrkadlo Karl Olsberg"),
  },
  {
    id: "kaputt",
    title: "Kaputt",
    author: "Wolfgang Münchau",
    cover: "/covers/007.webp",
    description: "Analýza konca nemeckého ekonomického zázraku a slabín povojnového modelu.",
    rating: null,
    source: martinusSearch("Kaputt Wolfgang Münchau"),
  },
  {
    id: "pruvodce-psychonauta",
    title: "Průvodce psychonauta",
    author: "James Fadiman",
    cover: "/covers/008.webp",
    description: "Praktický a historický pohľad na psychedeliká, ich výskum a zodpovedné používanie.",
    rating: null,
    source: martinusSearch("Průvodce psychonauta"),
  },
  {
    id: "thinking-in-systems",
    title: "Thinking in Systems",
    author: "Donella H. Meadows",
    cover: "/covers/009.webp",
    description: "Úvod do systémového myslenia, spätných väzieb a nečakaných dôsledkov rozhodnutí.",
    rating: null,
    source: martinusSearch("Thinking in Systems"),
  },
  {
    id: "beginning-of-infinity",
    title: "The Beginning of Infinity",
    author: "David Deutsch",
    cover: "/covers/010.webp",
    description: "O sile dobrých vysvetlení, pokroku a poznania, ktoré nemá prirodzený koniec.",
    rating: null,
    source: martinusSearch("The Beginning of Infinity"),
  },
  {
    id: "nastupci",
    title: "Nástupci",
    author: "Leoš Kyša",
    cover: "/covers/011.webp",
    description: "Zápisky zo sveta gerontokracie a príbeh generácie, ktorá má prevziať zodpovednosť.",
    rating: null,
    source: martinusSearch("Nástupci Leoš Kyša"),
  },
  {
    id: "priprav-svuj-mozek",
    title: "Připrav svůj mozek na éru AI",
    author: "Jon Finn",
    cover: "/covers/012.webp",
    description: "Ako si v čase AI pestovať sústredenie, učenie a mentálnu odolnosť.",
    rating: null,
    source: martinusSearch("Připrav svůj mozek na éru AI"),
  },
  {
    id: "antimemeticka-divize",
    title: "Antimemetická divize neexistuje",
    author: "qntm",
    cover: "/covers/013.webp",
    description: "Nápadité sci-fi o hrozbách, ktoré ľudská myseľ nedokáže udržať v pamäti.",
    rating: null,
    source: martinusSearch("Antimemetická divize neexistuje"),
  },
  {
    id: "more-beautiful-question",
    title: "A More Beautiful Question",
    author: "Warren Berger",
    cover: "/covers/014.webp",
    description: "Prečo dobré otázky odomykajú tvorivosť, inovácie a odvážnejšie rozhodnutia.",
    rating: null,
    source: martinusSearch("A More Beautiful Question"),
  },
  {
    id: "octopus-organization",
    title: "The Octopus Organization",
    author: "Phil Le-Brun a Jana Werner",
    cover: "/covers/015.webp",
    description: "Praktický model adaptívnej organizácie založenej na distribuovanej inteligencii.",
    rating: null,
    source: martinusSearch("The Octopus Organization"),
  },
  {
    id: "ekonomicke-instinkty",
    title: "Ekonomické instinkty",
    author: "Jan Urban",
    cover: "/covers/016.webp",
    description: "Behaviorálna ekonómia o tom, prečo sa často rozhodujeme proti vlastnému záujmu.",
    rating: null,
    source: martinusSearch("Ekonomické instinkty Jan Urban"),
  },
  {
    id: "zbohom-globalizacia",
    title: "Zbohom, globalizácia",
    author: "Peter Zeihan",
    cover: "/covers/017.webp",
    description: "Geopolitický pohľad na svet, v ktorom sa globálne dodávateľské reťazce rozpadajú.",
    rating: null,
    source: martinusSearch("Zbohom globalizácia"),
  },
  {
    id: "vynimocny-stav",
    title: "Výnimočný stav",
    author: "Martin M. Šimečka",
    cover: "/covers/018.webp",
    description: "Osobná esej o tom, ako v zlých časoch premýšľať, zachovať si slobodu a dobre žiť.",
    rating: null,
    source: martinusSearch("Výnimočný stav Martin M. Šimečka"),
  },
  {
    id: "karl-popper",
    title: "Karl Popper a vědecká racionalita",
    author: "Ondřej Biba",
    cover: "/covers/019.webp",
    description: "Filozofické skúmanie kritického racionalizmu a hraníc vedeckého poznania.",
    rating: null,
    source: martinusSearch("Karl Popper a vědecká racionalita"),
  },
  {
    id: "co-intelligence",
    title: "Co-Intelligence",
    author: "Ethan Mollick",
    cover: "/covers/020.webp",
    description: "Ako pracovať s AI ako s kolegom, učiteľom a partnerom bez straty úsudku.",
    rating: null,
    source: martinusSearch("Co-Intelligence Ethan Mollick"),
  },
  {
    id: "socialne-siete",
    title: "Sociálne siete musia byť zničené",
    author: "Samo Marec",
    cover: "/covers/021.webp",
    description: "Ako algoritmy škodia jednotlivcom aj spoločnosti a čo sa s tým ešte dá urobiť.",
    rating: 4.7,
    source: martinusSearch("Sociálne siete musia byť zničené"),
  },
  {
    id: "ako-pochopit-chudobu",
    title: "Ako pochopiť chudobu, keď máte peniaze",
    author: "Tim ’S Jongers",
    cover: "/covers/022.webp",
    description: "Výzva hovoriť o chudobe s ľuďmi, ktorých sa týka, nie iba o nich.",
    rating: null,
    source: martinusSearch("Ako pochopiť chudobu keď máte peniaze"),
  },
  {
    id: "velke-ekonomicke-dejiny",
    title: "Velké ekonomické dějiny",
    author: "Bernd Ziesemer",
    cover: "/covers/025.webp",
    description: "Široký príbeh hospodárstva od praveku po dnešnú globálnu ekonomiku.",
    rating: null,
    source: martinusSearch("Velké ekonomické dějiny"),
  },
  {
    id: "vek-kapitalismu-dohledu",
    title: "Věk kapitalismu dohledu",
    author: "Shoshana Zuboff",
    cover: "/covers/026.webp",
    description: "Zásadná analýza biznisu, ktorý premieňa ľudské správanie na zdroj dát a zisku.",
    rating: null,
    source: martinusSearch("Věk kapitalismu dohledu"),
  },
  {
    id: "cas-predatorov",
    title: "Čas predátorov",
    author: "Giuliano da Empoli",
    cover: "/covers/027.webp",
    description: "Esej o novej moci, technológiách a politikoch, ktorí menia pravidlá hry.",
    rating: null,
    source: martinusSearch("Čas predátorov"),
  },
  {
    id: "preco-si-nerozumieme",
    title: "Prečo si nerozumieme",
    author: "Vladimíra Čavojová a Jakub Šrol",
    cover: "/covers/029.webp",
    description: "Nenápadné presvedčenia očami psychológie a dôvody, prečo sa míňame v argumentoch.",
    rating: null,
    source: martinusSearch("Prečo si nerozumieme"),
  },
  {
    id: "misinformation",
    title: "Misinformation",
    author: "Sander van der Linden",
    cover: "/covers/030.webp",
    description: "Ako rozpoznávať manipulatívny obsah a odolávať dezinformáciám v digitálnom veku.",
    rating: null,
    source: martinusSearch("Misinformation Sander van der Linden"),
  },
  {
    id: "existencialny-manazment",
    title: "Existenciálny manažment",
    author: "Rastislav Silný",
    cover: "/covers/031.webp",
    description: "Rámec pre rozhodovanie a vedenie firmy v čase chaosu, neistoty a tlaku.",
    rating: null,
    source: martinusSearch("Existenciálny manažment"),
  },
  {
    id: "pedagogika-utlacovanych",
    title: "Pedagogika utlačovaných",
    author: "Paulo Freire",
    cover: "/covers/033.webp",
    description: "Klasika kritickej pedagogiky o vzdelávaní ako dialógu, slobode a zmene spoločnosti.",
    rating: null,
    source: martinusSearch("Pedagogika utlačovaných"),
  },
  {
    id: "slepe-miesta-mediciny",
    title: "Slepá místa medicíny",
    author: "Marty Makary",
    cover: "/covers/034.webp",
    description: "Lekársky pohľad na zaužívané omyly, neistotu a slepé miesta modernej medicíny.",
    rating: null,
    source: martinusSearch("Slepá místa medicíny Marty Makary"),
  },
  {
    id: "az-skonci-prace",
    title: "Až skončí práce",
    author: "Nick Srnicek a Helen Hester",
    cover: "/covers/035.webp",
    description: "Ako technológie, starostlivosť a automatizácia menia predstavu o práci a voľnom čase.",
    rating: null,
    source: martinusSearch("Až skončí práce"),
  },
  {
    id: "ziadne-kecy",
    title: "Žiadne kecy",
    author: "Ben Carpenter",
    cover: "/covers/037.webp",
    description: "Praktický sprievodca chudnutím bez zázračných diét, mýtov a jojo efektu.",
    rating: null,
    source: martinusSearch("Žiadne kecy Ben Carpenter"),
  },
  {
    id: "thousand-brains",
    title: "A Thousand Brains",
    author: "Jeff Hawkins",
    cover: "/covers/039.webp",
    description: "Nová teória inteligencie, mozgu a toho, ako si vytvárame model sveta.",
    rating: null,
    source: martinusSearch("A Thousand Brains"),
  },
  {
    id: "how-to-listen",
    title: "How to Listen",
    author: "Oscar Trimboli",
    cover: "/covers/040.webp",
    description: "Praktické techniky počúvania, ktoré zlepšujú porozumenie aj náročné rozhovory.",
    rating: null,
    source: martinusSearch("How to Listen Oscar Trimboli"),
  },
  {
    id: "prace-na-hovno",
    title: "Práce na hovno",
    author: "David Graeber",
    cover: "/covers/036.webp",
    description: "Provokatívna antropologická kritika nezmyselnej práce a jej spoločenských dôsledkov.",
    rating: null,
    source: martinusSearch("Práce na hovno David Graeber"),
  },
].sort((a, b) => a.title.localeCompare(b.title, "sk"));
