export type Book = {
  id: string;
  title: string;
  author: string;
  cover: string;
  description: string;
  rating: number | null;
  source: string;
};

const martinusSearch = (title: string) =>
  `https://www.martinus.sk/search?q=${encodeURIComponent(title)}`;

export const books: Book[] = [
  {
    id: "revolucionar-jednej-slamky",
    title: "Revolucionár jednej slamky",
    author: "Masanobu Fukuoka",
    cover: "/covers/001.webp",
    description: "Filozofia prirodzeného hospodárenia, jednoduchosti a života v súlade s krajinou.",
    rating: null,
    source: martinusSearch("Revolucionár jednej slamky"),
  },
  {
    id: "sedliacky",
    title: "Sedliačky",
    author: "Joanna Kuciel-Frydryszak",
    cover: "/covers/002.webp",
    description: "Silná reportáž o živote vidieckych žien, ich práci, chudobe a odolnosti.",
    rating: 4.6,
    source: "https://www.martinus.sk/3596167-sedliacky/kniha",
  },
  {
    id: "casozber",
    title: "Časozber",
    author: "Filip Langstein",
    cover: "/covers/003.webp",
    description: "Historické sci-fi o vedeckej výprave do dávnych epoch Zeme a nečakanom signále.",
    rating: null,
    source: "https://www.martinus.sk/3736605-casozber/kniha",
  },
  {
    id: "ubavit-se-k-smrti",
    title: "Ubavit se k smrti",
    author: "Neil Postman",
    cover: "/covers/004.webp",
    description: "Klasická kritika spoločnosti, v ktorej sa verejná diskusia mení na zábavu.",
    rating: null,
    source: martinusSearch("Ubavit se k smrti"),
  },
  {
    id: "cesta-do-mozgu-a-spat",
    title: "Cesta do mozgu a späť",
    author: "Dominika Fričová",
    cover: "/covers/005.webp",
    description: "Zrozumiteľný sprievodca mozgom: ako ho pochopiť, trénovať a upokojiť.",
    rating: null,
    source: "https://www.martinus.sk/3933935-cesta-do-mozgu-a-spat/e-kniha",
  },
  {
    id: "zrkadlo",
    title: "Zrkadlo",
    author: "Karl Olsberg",
    cover: "/covers/006.webp",
    description: "Technologický triler o umelej inteligencii, identite a hranici medzi človekom a strojom.",
    rating: null,
    source: martinusSearch("Zrkadlo Karl Olsberg"),
  },
  {
    id: "kaputt",
    title: "Kaputt",
    author: "Wolfgang Münchau",
    cover: "/covers/007.webp",
    description: "Analýza konca nemeckého ekonomického zázraku a slabín povojnového modelu.",
    rating: null,
    source: martinusSearch("Kaputt Wolfgang Münchau"),
  },
  {
    id: "pruvodce-psychonauta",
    title: "Průvodce psychonauta",
    author: "James Fadiman",
    cover: "/covers/008.webp",
    description: "Praktický a historický pohľad na psychedeliká, ich výskum a zodpovedné používanie.",
    rating: null,
    source: martinusSearch("Průvodce psychonauta"),
  },
  {
    id: "thinking-in-systems",
    title: "Thinking in Systems",
    author: "Donella H. Meadows",
    cover: "/covers/009.webp",
    description: "Úvod do systémového myslenia, spätných väzieb a nečakaných dôsledkov rozhodnutí.",
    rating: null,
    source: martinusSearch("Thinking in Systems"),
  },
  {
    id: "beginning-of-infinity",
    title: "The Beginning of Infinity",
    author: "David Deutsch",
    cover: "/covers/010.webp",
    description: "O sile dobrých vysvetlení, pokroku a poznania, ktoré nemá prirodzený koniec.",
    rating: null,
    source: martinusSearch("The Beginning of Infinity"),
  },
  {
    id: "nastupci",
    title: "Nástupci",
    author: "Leoš Kyša",
    cover: "/covers/011.webp",
    description: "Zápisky zo sveta gerontokracie a príbeh generácie, ktorá má prevziať zodpovednosť.",
    rating: null,
    source: martinusSearch("Nástupci Leoš Kyša"),
  },
  {
    id: "priprav-svuj-mozek",
    title: "Připrav svůj mozek na éru AI",
    author: "Jon Finn",
    cover: "/covers/012.webp",
    description: "Ako si v čase AI pestovať sústredenie, učenie a mentálnu odolnosť.",
    rating: null,
    source: martinusSearch("Připrav svůj mozek na éru AI"),
  },
  {
    id: "antimemeticka-divize",
    title: "Antimemetická divize neexistuje",
    author: "qntm",
    cover: "/covers/013.webp",
    description: "Nápadité sci-fi o hrozbách, ktoré ľudská myseľ nedokáže udržať v pamäti.",
    rating: null,
    source: martinusSearch("Antimemetická divize neexistuje"),
  },
  {
    id: "more-beautiful-question",
    title: "A More Beautiful Question",
    author: "Warren Berger",
    cover: "/covers/014.webp",
    description: "Prečo dobré otázky odomykajú tvorivosť, inovácie a odvážnejšie rozhodnutia.",
    rating: null,
    source: martinusSearch("A More Beautiful Question"),
  },
  {
    id: "octopus-organization",
    title: "The Octopus Organization",
    author: "Phil Le-Brun a Jana Werner",
    cover: "/covers/015.webp",
    description: "Praktický model adaptívnej organizácie založenej na distribuovanej inteligencii.",
    rating: null,
    source: martinusSearch("The Octopus Organization"),
  },
  {
    id: "ekonomicke-instinkty",
    title: "Ekonomické instinkty",
    author: "Jan Urban",
    cover: "/covers/016.webp",
    description: "Behaviorálna ekonómia o tom, prečo sa často rozhodujeme proti vlastnému záujmu.",
    rating: null,
    source: martinusSearch("Ekonomické instinkty Jan Urban"),
  },
  {
    id: "zbohom-globalizacia",
    title: "Zbohom, globalizácia",
    author: "Peter Zeihan",
    cover: "/covers/017.webp",
    description: "Geopolitický pohľad na svet, v ktorom sa globálne dodávateľské reťazce rozpadajú.",
    rating: null,
    source: martinusSearch("Zbohom globalizácia"),
  },
  {
    id: "vynimocny-stav",
    title: "Výnimočný stav",
    author: "Martin M. Šimečka",
    cover: "/covers/018.webp",
    description: "Osobná esej o tom, ako v zlých časoch premýšľať, zachovať si slobodu a dobre žiť.",
    rating: null,
    source: martinusSearch("Výnimočný stav Martin M. Šimečka"),
  },
  {
    id: "karl-popper",
    title: "Karl Popper a vědecká racionalita",
    author: "Ondřej Biba",
    cover: "/covers/019.webp",
    description: "Filozofické skúmanie kritického racionalizmu a hraníc vedeckého poznania.",
    rating: null,
    source: martinusSearch("Karl Popper a vědecká racionalita"),
  },
  {
    id: "co-intelligence",
    title: "Co-Intelligence",
    author: "Ethan Mollick",
    cover: "/covers/020.webp",
    description: "Ako pracovať s AI ako s kolegom, učiteľom a partnerom bez straty úsudku.",
    rating: null,
    source: martinusSearch("Co-Intelligence Ethan Mollick"),
  },
  {
    id: "socialne-siete",
    title: "Sociálne siete musia byť zničené",
    author: "Samo Marec",
    cover: "/covers/021.webp",
    description: "Ako algoritmy škodia jednotlivcom aj spoločnosti a čo sa s tým ešte dá urobiť.",
    rating: 4.7,
    source: martinusSearch("Sociálne siete musia byť zničené"),
  },
  {
    id: "ako-pochopit-chudobu",
    title: "Ako pochopiť chudobu, keď máte peniaze",
    author: "Tim ’S Jongers",
    cover: "/covers/022.webp",
    description: "Výzva hovoriť o chudobe s ľuďmi, ktorých sa týka, nie iba o nich.",
    rating: null,
    source: martinusSearch("Ako pochopiť chudobu keď máte peniaze"),
  },
  {
    id: "velke-ekonomicke-dejiny",
    title: "Velké ekonomické dějiny",
    author: "Bernd Ziesemer",
    cover: "/covers/025.webp",
    description: "Široký príbeh hospodárstva od praveku po dnešnú globálnu ekonomiku.",
    rating: null,
    source: martinusSearch("Velké ekonomické dějiny"),
  },
  {
    id: "vek-kapitalismu-dohledu",
    title: "Věk kapitalismu dohledu",
    author: "Shoshana Zuboff",
    cover: "/covers/026.webp",
    description: "Zásadná analýza biznisu, ktorý premieňa ľudské správanie na zdroj dát a zisku.",
    rating: null,
    source: martinusSearch("Věk kapitalismu dohledu"),
  },
  {
    id: "cas-predatorov",
    title: "Čas predátorov",
    author: "Giuliano da Empoli",
    cover: "/covers/027.webp",
    description: "Esej o novej moci, technológiách a politikoch, ktorí menia pravidlá hry.",
    rating: null,
    source: martinusSearch("Čas predátorov"),
  },
  {
    id: "preco-si-nerozumieme",
    title: "Prečo si nerozumieme",
    author: "Vladimíra Čavojová a Jakub Šrol",
    cover: "/covers/029.webp",
    description: "Nenápadné presvedčenia očami psychológie a dôvody, prečo sa míňame v argumentoch.",
    rating: null,
    source: martinusSearch("Prečo si nerozumieme"),
  },
  {
    id: "misinformation",
    title: "Misinformation",
    author: "Sander van der Linden",
    cover: "/covers/030.webp",
    description: "Ako rozpoznávať manipulatívny obsah a odolávať dezinformáciám v digitálnom veku.",
    rating: null,
    source: martinusSearch("Misinformation Sander van der Linden"),
  },
  {
    id: "existencialny-manazment",
    title: "Existenciálny manažment",
    author: "Rastislav Silný",
    cover: "/covers/031.webp",
    description: "Rámec pre rozhodovanie a vedenie firmy v čase chaosu, neistoty a tlaku.",
    rating: null,
    source: martinusSearch("Existenciálny manažment"),
  },
  {
    id: "pedagogika-utlacovanych",
    title: "Pedagogika utlačovaných",
    author: "Paulo Freire",
    cover: "/covers/033.webp",
    description: "Klasika kritickej pedagogiky o vzdelávaní ako dialógu, slobode a zmene spoločnosti.",
    rating: null,
    source: martinusSearch("Pedagogika utlačovaných"),
  },
  {
    id: "slepe-miesta-mediciny",
    title: "Slepá místa medicíny",
    author: "Marty Makary",
    cover: "/covers/034.webp",
    description: "Lekársky pohľad na zaužívané omyly, neistotu a slepé miesta modernej medicíny.",
    rating: null,
    source: martinusSearch("Slepá místa medicíny Marty Makary"),
  },
  {
    id: "az-skonci-prace",
    title: "Až skončí práce",
    author: "Nick Srnicek a Helen Hester",
    cover: "/covers/035.webp",
    description: "Ako technológie, starostlivosť a automatizácia menia predstavu o práci a voľnom čase.",
    rating: null,
    source: martinusSearch("Až skončí práce"),
  },
  {
    id: "ziadne-kecy",
    title: "Žiadne kecy",
    author: "Ben Carpenter",
    cover: "/covers/037.webp",
    description: "Praktický sprievodca chudnutím bez zázračných diét, mýtov a jojo efektu.",
    rating: null,
    source: martinusSearch("Žiadne kecy Ben Carpenter"),
  },
  {
    id: "thousand-brains",
    title: "A Thousand Brains",
    author: "Jeff Hawkins",
    cover: "/covers/039.webp",
    description: "Nová teória inteligencie, mozgu a toho, ako si vytvárame model sveta.",
    rating: null,
    source: martinusSearch("A Thousand Brains"),
  },
  {
    id: "how-to-listen",
    title: "How to Listen",
    author: "Oscar Trimboli",
    cover: "/covers/040.webp",
    description: "Praktické techniky počúvania, ktoré zlepšujú porozumenie aj náročné rozhovory.",
    rating: null,
    source: martinusSearch("How to Listen Oscar Trimboli"),
  },
  {
    id: "prace-na-hovno",
    title: "Práce na hovno",
    author: "David Graeber",
    cover: "/covers/036.webp",
    description: "Provokatívna antropologická kritika nezmyselnej práce a jej spoločenských dôsledkov.",
    rating: null,
    source: martinusSearch("Práce na hovno David Graeber"),
  },
  {
    id: "brain-code",
    title: "The Brain Code",
    author: "Yossi Chalamish",
    cover: "/covers/041.webp",
    description: "Praktický pohľad na fungovanie mozgu, učenie, sústredenie a duševnú výkonnosť.",
    rating: null,
    source: martinusSearch("The Brain Code Yossi Chalamish"),
  },
  {
    id: "winning-war-in-your-mind",
    title: "Winning the War in Your Mind",
    author: "Craig Groeschel",
    cover: "/covers/042.webp",
    description: "Ako rozpoznať škodlivé myšlienkové vzorce a nahradiť ich zdravšími návykmi.",
    rating: null,
    source: martinusSearch("Winning the War in Your Mind Craig Groeschel"),
  },
  {
    id: "2084-ai-revolution",
    title: "2084 and the AI Revolution",
    author: "John C. Lennox",
    cover: "/covers/043.webp",
    description: "Úvaha o umelej inteligencii, budúcnosti ľudstva a etických hraniciach technológií.",
    rating: null,
    source: martinusSearch("2084 and the AI Revolution John Lennox"),
  },
  {
    id: "if-anyone-builds-it",
    title: "If Anyone Builds It, Everyone Dies",
    author: "Eliezer Yudkowsky a Nate Soares",
    cover: "/covers/044.webp",
    description: "Argument proti vývoju superinteligentnej AI bez spoľahlivej kontroly jej cieľov.",
    rating: null,
    source: martinusSearch("If Anyone Builds It Everyone Dies"),
  },
  {
    id: "science-rapid-skill-acquisition",
    title: "The Science of Rapid Skill Acquisition",
    author: "Peter Hollins",
    cover: "/covers/045.webp",
    description: "Metódy rýchlejšieho osvojovania zručností, tréningu a zámerného precvičovania.",
    rating: null,
    source: martinusSearch("The Science of Rapid Skill Acquisition"),
  },
  {
    id: "polymath",
    title: "Polymath",
    author: "Peter Hollins",
    cover: "/covers/046.webp",
    description: "Návod, ako rozvíjať viacero schopností a prepájať poznatky z rôznych oblastí.",
    rating: null,
    source: martinusSearch("Polymath Peter Hollins"),
  },
  {
    id: "prilis-mnoho-a-nikdy-dost",
    title: "Příliš mnoho a nikdy dost",
    author: "Mary L. Trump",
    cover: "/covers/048.webp",
    description: "Rodinná výpoveď o prostredí, ktoré formovalo Donalda Trumpa a jeho vzťah k moci.",
    rating: null,
    source: martinusSearch("Příliš mnoho a nikdy dost Mary Trump"),
  },
  {
    id: "sila-zlozvyku",
    title: "Sila zlozvyku",
    author: "Nicklas Brendborg",
    cover: "/covers/049.webp",
    description: "Vedecký pohľad na návykové správanie a mechanizmy, ktoré riadia naše rozhodnutia.",
    rating: null,
    source: martinusSearch("Sila zlozvyku Nicklas Brendborg"),
  },
  {
    id: "umeni-skoncit",
    title: "Umění skončit",
    author: "Annie Duke",
    cover: "/covers/051.webp",
    description: "Ako včas opustiť nefungujúci plán a robiť lepšie rozhodnutia bez pocitu zlyhania.",
    rating: null,
    source: martinusSearch("Umění skončit Annie Duke"),
  },
  {
    id: "stan-sa-neznicitelnym",
    title: "Staň sa nezničiteľným",
    author: "Evy Poumpouras",
    cover: "/covers/052.webp",
    description: "Skúsenosti bývalej agentky o odolnosti, bezpečí a zvládaní náročných situácií.",
    rating: null,
    source: martinusSearch("Staň sa nezničiteľným Evy Poumpouras"),
  },
  {
    id: "scaling-up",
    title: "Scaling Up",
    author: "Verne Harnish",
    cover: "/covers/053.webp",
    description: "Systém rastu firmy cez ľudí, stratégiu, realizáciu a zdravé riadenie financií.",
    rating: null,
    source: martinusSearch("Scaling Up Verne Harnish"),
  },
  {
    id: "proc-staty-selhavaji",
    title: "Proč státy selhávají",
    author: "Daron Acemoglu a James A. Robinson",
    cover: "/covers/055.webp",
    description: "Prečo inkluzívne inštitúcie prinášajú prosperitu a extraktívne systémy úpadok.",
    rating: null,
    source: martinusSearch("Proč státy selhávají"),
  },
  {
    id: "zmente-otazky-zmente-zivot",
    title: "Změňte otázky, změňte svůj život",
    author: "Marilee Adams",
    cover: "/covers/057.webp",
    description: "Ako kvalita otázok ovplyvňuje naše vzťahy, rozhodovanie aj schopnosť učiť sa.",
    rating: null,
    source: martinusSearch("Změňte otázky změňte svůj život Marilee Adams"),
  },
  {
    id: "nenasilna-komunikace-zakladni-myslenky",
    title: "Nenásilná komunikace – základní myšlenky",
    author: "Marshall B. Rosenberg",
    cover: "/covers/058.webp",
    description: "Krátke texty o empatii, potrebách a rozhovoroch bez nátlaku či obviňovania.",
    rating: null,
    source: martinusSearch("Nenásilná komunikace základní myšlenky"),
  },
  {
    id: "nehovor-hmm",
    title: "Nehovor hmm",
    author: "Michael Chad Hoeppner",
    cover: "/covers/061.webp",
    description: "Rýchla metóda na jasnejšie, sebavedomejšie a účinnejšie vyjadrovanie.",
    rating: null,
    source: martinusSearch("Nehovor hmm Michael Chad Hoeppner"),
  },
  {
    id: "bezohledni-lide",
    title: "Bezohlední lidé",
    author: "Sarah Wynn-Williams",
    cover: "/covers/063.webp",
    description: "Insiderská výpoveď o fungovaní Facebooku, jeho kultúre a globálnom vplyve.",
    rating: null,
    source: martinusSearch("Bezohlední lidé Sarah Wynn-Williams"),
  },
  {
    id: "umeni-vnimat-problemy",
    title: "Umění vnímat problémy pro děti a rodiče",
    author: "Michael Třeštík",
    cover: "/covers/064.webp",
    description: "Podnety pre spoločné premýšľanie rodičov a detí o zložitých témach sveta.",
    rating: null,
    source: martinusSearch("Umění vnímat problémy pro děti a rodiče"),
  },
  {
    id: "12-strategii-trida-ai",
    title: "12 strategií pro každou třídu ve věku AI",
    author: "Monica Burns",
    cover: "/covers/065.webp",
    description: "Praktický sprievodca zmysluplným a bezpečným využitím AI vo vyučovaní.",
    rating: null,
    source: martinusSearch("12 strategií pro každou třídu ve věku AI"),
  },
  {
    id: "nazi-v-ai-dobe",
    title: "Nazí v AI době",
    author: "Lukáš Sedlák",
    cover: "/covers/066.webp",
    description: "O tom, čo umelá inteligencia odhaľuje o ľuďoch, práci a súčasnej spoločnosti.",
    rating: null,
    source: martinusSearch("Nazí v AI době Lukáš Sedlák"),
  },
  {
    id: "atlasova-vzpoura",
    title: "Atlasova vzpoura",
    author: "Ayn Rand",
    cover: "/covers/067.webp",
    description: "Rozsiahly román o individualizme, moci, tvorivosti a úlohe schopných jednotlivcov.",
    rating: null,
    source: martinusSearch("Atlasova vzpoura Ayn Rand"),
  },
  {
    id: "120-navrhov-zachranit-svet",
    title: "120 návrhov ako zachrániť svet",
    author: "Richard Weller",
    cover: "/covers/069.webp",
    description: "Atlas konkrétnych zásahov a projektov pre udržateľnejšiu budúcnosť planéty.",
    rating: null,
    source: martinusSearch("120 návrhov ako zachrániť svet"),
  },
  {
    id: "konec-skolni-nudy",
    title: "Konec školní nudy",
    author: "Spencer Kagan",
    cover: "/covers/070.webp",
    description: "Didaktické metódy, ktoré zapájajú žiakov a premieňajú pasívnu výučbu na spoluprácu.",
    rating: null,
    source: martinusSearch("Konec školní nudy Spencer Kagan"),
  },
  {
    id: "zesilet-v-divocine",
    title: "Zesílet v divočině",
    author: "Aleš Palán",
    cover: "/covers/072.webp",
    description: "Rozhovory a príbehy ľudí, ktorým samota a príroda pomohli zmeniť život.",
    rating: null,
    source: martinusSearch("Zesílet v divočině Aleš Palán"),
  },
  {
    id: "pretizeny",
    title: "Přetíženy",
    author: "Kateřina Trávníčková a Martina Mašková",
    cover: "/covers/073.webp",
    description: "O neviditeľnej mentálnej záťaži žien, vyčerpaní a spravodlivejšom delení povinností.",
    rating: null,
    source: martinusSearch("Přetíženy Trávníčková Mašková"),
  },
  {
    id: "teoria-zahalcivej-triedy",
    title: "Teória zahálčivej triedy",
    author: "Thorstein Veblen",
    cover: "/covers/076.webp",
    description: "Klasická kritika okázalej spotreby, spoločenského statusu a ekonomických elít.",
    rating: null,
    source: martinusSearch("Teória zahálčivej triedy Thorstein Veblen"),
  },
  {
    id: "prumysl-lzi",
    title: "Průmysl lži",
    author: "Alexandra Alvarová",
    cover: "/covers/078.webp",
    description: "Ako propaganda, manipulácia a digitálne platformy formujú verejnú mienku.",
    rating: null,
    source: martinusSearch("Průmysl lži Alexandra Alvarová"),
  },
  {
    id: "skutocna-skryta-pravda-o-svete",
    title: "Skutočná skrytá pravda o svete",
    author: "David Graeber",
    cover: "/covers/079.webp",
    description: "Výber esejí o moci, práci, byrokracii a alternatívach k zaužívanému poriadku.",
    rating: null,
    source: martinusSearch("Skutočná skrytá pravda o svete David Graeber"),
  },
  {
    id: "algospeak",
    title: "Algospeak",
    author: "Adam Aleksic",
    cover: "/covers/081.webp",
    description: "Ako algoritmy sociálnych sietí menia jazyk, slang a spôsob online komunikácie.",
    rating: null,
    source: martinusSearch("Algospeak Adam Aleksic"),
  },
  {
    id: "zivot-3-0",
    title: "Život 3.0",
    author: "Max Tegmark",
    cover: "/covers/083.webp",
    description: "Úvaha o inteligencii, vedomí a možnostiach ľudstva vo veku umelej inteligencie.",
    rating: null,
    source: martinusSearch("Život 3.0 Max Tegmark"),
  },
  {
    id: "everest-s-rucenim-obmedzenym",
    title: "Everest s ručením obmedzeným",
    author: "Will Cockrell",
    cover: "/covers/084.webp",
    description: "Dejiny komercializácie Everestu, dobrodružstva, rizika a vysokohorskej turistiky.",
    rating: null,
    source: martinusSearch("Everest s ručením obmedzeným Will Cockrell"),
  },
  {
    id: "hlasy-priepasti",
    title: "Hlasy priepasti",
    author: "Dušan Valent",
    cover: "/covers/085.webp",
    description: "Výprava do hlbín poznania, prírody a tajomstiev, ktoré preverujú ľudskú zvedavosť.",
    rating: null,
    source: martinusSearch("Hlasy priepasti Dušan Valent"),
  },
  {
    id: "samko-tale",
    title: "Samko Tále: Kniha o cintoríne",
    author: "Daniela Kapitáňová",
    cover: "/covers/086.webp",
    description: "Tragikomický monológ malomestského rozprávača a satira na slovenskú spoločnosť.",
    rating: null,
    source: martinusSearch("Samko Tále Kniha o cintoríne"),
  },
  {
    id: "nase-tela",
    title: "Naše těla",
    author: "Juan Luis Arsuaga",
    cover: "/covers/088.webp",
    description: "Sedem miliónov rokov evolúcie ľudského tela podaných zrozumiteľne a pútavo.",
    rating: null,
    source: martinusSearch("Naše těla Juan Luis Arsuaga"),
  },
  {
    id: "dnes-trochu-umreme",
    title: "Dnes trochu umřeme",
    author: "Richard Askwith",
    cover: "/covers/090.webp",
    description: "Životný príbeh Emila Zátopka, jeho športových triumfov, odvahy a pádu.",
    rating: null,
    source: martinusSearch("Dnes trochu umřeme Richard Askwith"),
  },
  {
    id: "svetovi-intelektualove",
    title: "Světoví intelektuálové",
    author: "Redakce týdeníku Respekt",
    cover: "/covers/094.webp",
    description: "Sprievodca osobnosťami a myšlienkami, ktoré pomáhajú chápať nepokojnú dobu.",
    rating: null,
    source: martinusSearch("Světoví intelektuálové Respekt"),
  },
  {
    id: "kolko-stoji-vase-stastie",
    title: "Koľko stojí vaše šťastie?",
    author: "Juraj Hrbatý, Ján Tonka a Simon Pekar",
    cover: "/covers/096.webp",
    description: "Desať krokov k zdravšiemu vzťahu k peniazom, bohatstvu a osobnej spokojnosti.",
    rating: null,
    source: martinusSearch("Koľko stojí vaše šťastie"),
  },
  {
    id: "heureka",
    title: "Heuréka!",
    author: "Tomáš Braverman",
    cover: "/covers/097.webp",
    description: "Príbeh budovania Heuréky a lekcie o raste, vedení a škálovaní technologickej firmy.",
    rating: null,
    source: martinusSearch("Heuréka Tomáš Braverman"),
  },
  {
    id: "upracte-si-svoj-zivot",
    title: "Uprac si svoj život",
    author: "Tyler Moore",
    cover: "/covers/098.webp",
    description: "Jemný systém organizácie domácnosti a návykov bez perfekcionizmu a preťaženia.",
    rating: null,
    source: martinusSearch("Uprac si svoj život Tyler Moore"),
  },
  {
    id: "hejtovania",
    title: "#hejtovania",
    author: "Viliam Klimáček",
    cover: "/covers/102.webp",
    description: "Satirický pohľad na nenávisť, sociálne siete a rozdelenú súčasnú spoločnosť.",
    rating: null,
    source: martinusSearch("hejtovania Viliam Klimáček"),
  },
  {
    id: "how-to-think-about-ai",
    title: "How to Think About AI",
    author: "Richard Susskind",
    cover: "/covers/104.webp",
    description: "Rámec na realistické premýšľanie o možnostiach, rizikách a regulácii AI.",
    rating: null,
    source: martinusSearch("How to Think About AI Richard Susskind"),
  },
  {
    id: "ako-vediet-vsetko",
    title: "Ako vedieť všetko",
    author: "Elke Wiss",
    cover: "/covers/107.webp",
    description: "Ako sa lepšími otázkami dostať k presnejším odpovediam a hlbšiemu porozumeniu.",
    rating: null,
    source: martinusSearch("Ako vedieť všetko Elke Wiss"),
  },
  {
    id: "svet-na-predaj",
    title: "Svet na predaj",
    author: "Javier Blas a Jack Farchy",
    cover: "/covers/108.webp",
    description: "Príbeh obchodníkov s komoditami, ktorí získali obrovský vplyv na svetovú ekonomiku.",
    rating: null,
    source: martinusSearch("Svet na predaj Javier Blas Jack Farchy"),
  },
  {
    id: "muz-ktery-rozdava-stesti",
    title: "Muž, který rozdává štěstí",
    author: "Biyon Kattilathu",
    cover: "/covers/110.webp",
    description: "Inšpiratívne príbehy o radosti, vzťahoch a malých rozhodnutiach, ktoré menia život.",
    rating: null,
    source: martinusSearch("Muž který rozdává štěstí Biyon Kattilathu"),
  },
  {
    id: "strata-kontroly",
    title: "Strata kontroly",
    author: "Eric Schlosser",
    cover: "/covers/111.webp",
    description: "Investigatívny pohľad na jadrové zbrane, bezpečnostné zlyhania a riziko katastrofy.",
    rating: null,
    source: martinusSearch("Strata kontroly Eric Schlosser"),
  },
  {
    id: "trenovani-pameti",
    title: "Trénování paměti a poznávacích schopností",
    author: "Marek Preiss a Jaro Křivohlavý",
    cover: "/covers/112.webp",
    description: "Cvičenia a postupy na podporu pamäti, pozornosti a ďalších kognitívnych schopností.",
    rating: null,
    source: martinusSearch("Trénování paměti a poznávacích schopností"),
  },
  {
    id: "jak-se-uspesne-ucit",
    title: "Jak se úspěšně učit",
    author: "Eberhard Hofmann a Monika Löhle",
    cover: "/covers/113.webp",
    description: "Overené stratégie učenia, plánovania, opakovania a práce s motiváciou.",
    rating: null,
    source: martinusSearch("Jak se úspěšně učit Hofmann Löhle"),
  },
  {
    id: "post-pravdovy-svet",
    title: "Post-pravdový svět",
    author: "Ken Wilber",
    cover: "/covers/115.webp",
    description: "Analýza polarizácie, kultúrnych konfliktov a cesty z postpravdivého chaosu.",
    rating: null,
    source: martinusSearch("Post-pravdový svět Ken Wilber"),
  },
  {
    id: "imunomysel",
    title: "Imunomysel",
    author: "Monty Lyman",
    cover: "/covers/118.webp",
    description: "Ako spolu komunikujú imunitný systém, mozog a psychika a čo to znamená pre zdravie.",
    rating: null,
    source: martinusSearch("Imunomysel Monty Lyman"),
  },
  {
    id: "dvojnice",
    title: "Dvojnice",
    author: "Naomi Klein",
    cover: "/covers/119.webp",
    description: "Osobná cesta zrkadlovým svetom konšpirácií, polarizácie a digitálnej identity.",
    rating: null,
    source: martinusSearch("Dvojnice Naomi Klein"),
  },
  {
    id: "digitalni-minimalismus",
    title: "Digitální minimalismus",
    author: "Cal Newport",
    cover: "/covers/121.webp",
    description: "Ako si zvoliť technológie zámerne a získať späť pozornosť, pokoj a čas.",
    rating: null,
    source: martinusSearch("Digitální minimalismus Cal Newport"),
  },
  {
    id: "think-like-super-gm",
    title: "Think Like a Super-GM",
    author: "Michael Adams a Philip Hurtado",
    cover: "/covers/124.webp",
    description: "Šachové pozície a vysvetlenia, ktoré odhaľujú spôsob myslenia veľmajstrov.",
    rating: null,
    source: martinusSearch("Think Like a Super-GM"),
  },
  {
    id: "teorie-her",
    title: "Teorie her",
    author: "Ken Binmore",
    cover: "/covers/126.webp",
    description: "Stručný úvod do strategického rozhodovania, spolupráce, konfliktu a motivácií.",
    rating: null,
    source: martinusSearch("Teorie her Ken Binmore"),
  },
  {
    id: "ako-sa-dohovorit",
    title: "Ako sa dohovoriť",
    author: "Jefferson Fisher",
    cover: "/covers/127.webp",
    description: "Praktické zásady pokojnej a pevnej komunikácie v náročných rozhovoroch.",
    rating: null,
    source: martinusSearch("Ako sa dohovoriť Jefferson Fisher"),
  },
  {
    id: "ako-vysvetlit-svet",
    title: "Ako vysvetliť svet",
    author: "Steven Weinberg",
    cover: "/covers/129.webp",
    description: "Dejiny modernej vedy a cesta od starých predstáv k vedeckému vysvetľovaniu sveta.",
    rating: null,
    source: martinusSearch("Ako vysvetliť svet Steven Weinberg"),
  },
  {
    id: "ohen-nad-hlubinou",
    title: "Oheň nad hlubinou",
    author: "Vernor Vinge",
    cover: "/covers/130.webp",
    description: "Veľkolepé space opera sci-fi o superinteligencii, civilizáciách a boji o prežitie.",
    rating: null,
    source: martinusSearch("Oheň nad hlubinou Vernor Vinge"),
  },
  {
    id: "uz-zadne-drama",
    title: "Už žádné drama",
    author: "Nedra Glover Tawwab",
    cover: "/covers/132.webp",
    description: "Ako rozpoznať nezdravé rodinné vzorce, nastavovať hranice a chrániť svoj pokoj.",
    rating: null,
    source: martinusSearch("Už žádné drama Nedra Glover Tawwab"),
  },
  {
    id: "umeni-neuspechu",
    title: "Umění neúspěchu",
    author: "Josef Hynek a Tomáš Studeník",
    cover: "/covers/133.webp",
    description: "Príbehy vedeckých omylov a zlyhaní, z ktorých vyrástli dôležité objavy.",
    rating: null,
    source: martinusSearch("Umění neúspěchu Hynek Studeník"),
  },
  {
    id: "muj-kousek-himalaje",
    title: "Můj kousek Himálaje",
    author: "Štěpánka Címlová",
    cover: "/covers/134.webp",
    description: "Osobný príbeh horskej výzvy, vytrvalosti a hľadania vlastných hraníc.",
    rating: null,
    source: martinusSearch("Můj kousek Himálaje Štěpánka Címlová"),
  },
  {
    id: "krok-za-krokem-zdravejsi-mozek",
    title: "Krok za krokem ke zdravějšímu mozku",
    author: "Daniel Amen",
    cover: "/covers/135.webp",
    description: "Konkrétne kroky na podporu mozgu prostredníctvom spánku, pohybu, stravy a návykov.",
    rating: null,
    source: martinusSearch("Krok za krokem ke zdravějšímu mozku Daniel Amen"),
  },
  {
    id: "pocuvanie-ako-superschopnost",
    title: "Počúvanie ako superschopnosť",
    author: "Patrick King",
    cover: "/covers/136.webp",
    description: "Techniky aktívneho počúvania pre lepšie vzťahy, rozhovory a porozumenie.",
    rating: null,
    source: martinusSearch("Počúvanie ako superschopnosť Patrick King"),
  },
  {
    id: "prechadzka-v-parku",
    title: "Prechádzka v parku",
    author: "Kevin Fedarko",
    cover: "/covers/137.webp",
    description: "Dobrodružná pešia cesta naprieč Grand Canyonom a príbeh krajiny pod tlakom.",
    rating: null,
    source: martinusSearch("Prechádzka v parku Kevin Fedarko"),
  },
  {
    id: "takticke-mysleni",
    title: "Taktické myšlení",
    author: "Charles Phillips",
    cover: "/covers/141.webp",
    description: "Súbor úloh na precvičenie logiky, plánovania, stratégie a riešenia problémov.",
    rating: null,
    source: martinusSearch("Taktické myšlení Charles Phillips"),
  },
  {
    id: "vek-revolucii",
    title: "Vek revolúcií",
    author: "Fareed Zakaria",
    cover: "/covers/142.webp",
    description: "Ako technologické, ekonomické a politické revolúcie menili svet a formujú dnešok.",
    rating: null,
    source: martinusSearch("Vek revolúcií Fareed Zakaria"),
  },
  {
    id: "high-conflict",
    title: "High Conflict",
    author: "Amanda Ripley",
    cover: "/covers/143.webp",
    description: "Prečo sa konflikty menia na pasce a ako sa z nich jednotlivci aj skupiny dostávajú.",
    rating: null,
    source: martinusSearch("High Conflict Amanda Ripley"),
  },
  {
    id: "80-na-kazdy-den",
    title: "80 na každý deň",
    author: "Richard Koch",
    cover: "/covers/144.webp",
    description: "Každodenné lekcie princípu 80/20 pre zdravie, prácu, rozhodovanie a spokojnosť.",
    rating: null,
    source: martinusSearch("80 na každý deň Richard Koch"),
  },
  {
    id: "kriticke-mysleni-jiri-sedy",
    title: "Kritické myšlení",
    author: "Jiří Šedý",
    cover: "/covers/145.webp",
    description: "Praktický pohľad na nezávislé posudzovanie problémov, kognitívne skreslenia a každodenné rozhodovanie.",
    rating: null,
    source: martinusSearch("Kritické myšlení Jiří Šedý"),
  },
  {
    id: "reportaz-o-turistickom-priemysle",
    title: "Reportáž o turistickom priemysle",
    author: "Jennie Dielemans",
    cover: "/covers/146.webp",
    description: "Investigatívna reportáž o tom, ako cestovný ruch pretvára krajinu, komunity a predstavu o nedotknutom svete.",
    rating: null,
    source: martinusSearch("Reportáž o turistickom priemysle Jennie Dielemans"),
  },
  {
    id: "solving-problems-with-design-thinking",
    title: "Solving Problems with Design Thinking",
    author: "Jeanne Liedtka, Andrew King a Kevin Bennett",
    cover: "/covers/147.webp",
    description: "Desať prípadových štúdií ukazuje, ako organizácie využívajú dizajnové myslenie na riešenie praktických problémov.",
    rating: null,
    source: martinusSearch("Solving Problems with Design Thinking Liedtka King Bennett"),
  },
  {
    id: "na-ctyrech",
    title: "Na čtyřech",
    author: "Miranda July",
    cover: "/covers/148.webp",
    description: "Vtipný a odvážny román o štyridsaťpäťročnej umelkyni, ktorá počas cesty prehodnotí slobodu, intimitu aj rodinný život.",
    rating: null,
    source: "https://www.martinus.sk/2891509-all-fours/kniha",
  },
  {
    id: "anatomie-rozhodovani",
    title: "Anatomie rozhodování",
    author: "Richard Shotton",
    cover: "/covers/149.webp",
    description: "Zrozumiteľný pohľad na psychologické skreslenia a sily, ktoré ovplyvňujú každodenné aj nákupné rozhodnutia.",
    rating: null,
    source: martinusSearch("Anatomie rozhodování Richard Shotton"),
  },
  {
    id: "spin-diktatori",
    title: "Spin diktátoři",
    author: "Sergej Gurijev a Daniel Treisman",
    cover: "/covers/150.webp",
    description: "Analýza moderných autoritárov, ktorí si moc udržiavajú manipuláciou informácií a predstieraním demokratických postupov.",
    rating: null,
    source: "https://www.martinus.sk/3703169-spin-diktatori/e-kniha",
  },
].sort((a, b) => a.title.localeCompare(b.title, "sk"));
